project_id = "hvwhhotclhakfyxbwxlk"

[functions.keep-alive]
verify_jwt = false

[functions.auto-approve-shipments]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.create-user-with-password]
verify_jwt = false

[functions.create-user-profile]
verify_jwt = false

[functions.submit-company-registration]
verify_jwt = false